include "default-core"
include "application-dev.conf"

#feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorNews"

detector {
    did = "DetectorNews"

    contract="Twitter-War"
    chain=""

    conf="""{
        "cron": "150000",
        "desc": "New post: >>>>>>>>>>>>> {title}{err}",

        "type": "twitter",
        "feeds": "twitter://GeneralStaffUA",

        "max": 15,
        "max_seen_posts": 100,

        "threshold": "",

        "script": [
            {
                "type": "regexp",
                "src": ".*Загальні бойові втрати противника.*"
            }, 
            {
                "type": "filter",
                "src": ""
            },
            {
                "type": "js",
                "src": "'image://' + images.split(',')[0]"
            },
            {
                "type": "ai",
                "src": "Extract text from provided image {input} and return result as json. output://json_object",
                "options": "openai://?timeout=60000"
            }
        ],

        "track_err": true,
        "err_always": true
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
