include "default-core"
include "application-dev.conf"

#feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorFeed"

# Comma-separated feed URIs (file:// or https://)
# Examples:
  #   file://./rss/coingtelegraph-all.rss.xml
  #   https://cointelegraph.com/rss
  #   file://./reddit/reddit-1.xml
  #   https://www.reddit.com/domain/howtogeek.com.rss
  #   https://www.coindesk.com/arc/outboundfeeds/rss/

# "feeds":"https://cointelegraph.com/rss",
# "feeds":"https://blockworks.co/feed/",

detector {
    did = "DetectorFeed"

    contract="News-Meltwater"
    chain=""

    conf="""{        
        "category":"",
        "cron":"1 day",
        "desc":"{title}{err}",

        "track_err":true,
        "err_always":true,

        "event_cat":"DATA",
        "event_sid":"ext:data",
        "event_type":"feed",

        "type":"meltwater",
        "feeds":"file://./meltwater/28737363-10.json",

        "max":300,
        
        "script":[],
        "score":">= 0",

        "severity":-1
        
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
