include "default-core"

detectors="""
    io.syspulse.ext.sentinel.DetectorWar
    """

detector {
    did = "DetectorWar"

    contract="War-Report-1"
    chain=""

    conf="""{
        "cron": "150000",
        "desc": "Report: >>>>>>>>>>>>> {loss_personnel_total} {err}",

        "custom_regexp": "",
                
        "track_err": true,
        "err_always": true
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
