include "default-core"
include "application-dev.conf"

feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorNews"

# "event_type": "___sentry___",
#         "event_cat": "DATA",
#         "event_sid": "EXT:sentinel",

detector {
    did = "DetectorNews"

    contract="News-RSS"
    chain=""

    conf="""{
        "cron": "1000",
        "desc": ">>>>>>>>>>>>>>>>>>>>>>>>>>>> {title}{err}",

        "type": "news",
        "feeds": "file://./rss/coingtelegraph-all.rss",

        "max": 1,
        "max_seen_posts": 100,

        "threshold": "> 0",

        "script": [

        ],

        "event_type": "TTTTTT",
        "event_cat": "CCCCCCCCCCCCCCC",
        "event_sid": "IIIIIIIIIIIIIIIIIIIIIIII",

        "track_err": true,
        "err_always": true
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"    
    
}
