include "default-core"
include "application-dev.conf"

#feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorFeed"

detector {
    did = "DetectorFeed"

    contract="News-RSS"
    chain=""

    conf="""{        
        "category":"",
        "cron":"1 day",
        "desc":"{title}{err}",        

        "event_cat":"DATA",
        "event_sid":"ext:data",
        "event_type":"feed",

        "feeds":"rss://https://cointelegraph.com/rss, rss://https://www.theblock.co/rss.xml, rss://https://decrypt.co/feed",
        "type":"rss",

        "max":2,

        "score":"> 0",

        "script":[
            {
                "type": "js",
                "src": "1.0;"
            }
        ],

        "severity":-1,
        
        "track_err":true,
        "err_always":true
        
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
