include "default-core"
include "application-dev.conf"

#feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorNews"

# Comma-separated feed URIs (file:// or https://)
# Examples:
  #   file://./rss/coingtelegraph-all.rss.xml
  #   https://cointelegraph.com/rss
  #   file://./reddit/reddit-1.xml
  #   https://www.reddit.com/domain/howtogeek.com.rss
  #   https://www.coindesk.com/arc/outboundfeeds/rss/

detector {
    did = "DetectorNews"

    contract="News-RSS"
    chain=""

    conf="""{
        "cron": "15000",
        "desc": "New post: >>>>>>>>>>>>> {title}{err}",

        "type": "twitter",
        "feeds": "twitter://hackenclub",

        "max": 5,
        "max_seen_posts": 100,

        "threshold": ">= 0.5",

        "script": [
            {
                "type": "js",
                "src": "(input && input.indexOf('@0xJonnyDee') >= 0) ? '1.0' : ((author && author.indexOf('@0xJonnyDee') >= 0) ? '1.0' : '0.0')"
            }
        ],

        "track_err": true,
        "err_always": true
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
