include "default-core"
include "application-dev.conf"

#feed="null://"
# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorFeed"


detector {
    did = "DetectorFeed"

    contract="News-Meltwater-API"
    chain=""

    conf="""{        
        "category":"",
        "cron":"1 day",
        "desc":"{title}{err}",

        "track_err":true,
        "err_always":true,

        "event_cat":"DATA",
        "event_sid":"ext:data",
        "event_type":"feed",

        "type":"meltwater",
        "feeds":"meltwater://28737363?apiKey={MELTWATER_API_KEY}",

        "max":5,
        
        "script":[],
        "score":">= 0",

        "severity":-1
        
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
