include "default-core"

# output="kafka://kafka:9092/event"

detectors="io.syspulse.ext.sentinel.DetectorSnapshotGov"

detector {
    did = "DetectorSnapshotGov"

    contract="Snapshot Governance"

    conf="""{
        "cron":"10000",
        "space": "aavedao.eth",
        "proposal_count": 10,
        "track_active": true,
        "track_closed": true,
        "track_pending": false
    }"""

    feed="kafka://localhost:9092/detector.sync/test-0001/END"
    output="err://"
}
