include "default-core"
include "application-dev.conf"

# output="kafka://kafka:9092/event"

detectors="io.syspulse.ext.sentinel.DetectorSnapshotGov"

detector {
    did = "DetectorSnapshotGov"

    contract="Snapshot Governance"

    conf="""{
        "cron":"30000",
        "space": "aavedao.eth",
        "proposal_count": 10,
        "track_active": true,
        "track_closed": true,
        "track_pending": true
    }"""
    
    output="err://"
}
