include "default-core"

detectors="""
    io.syspulse.ext.sentinel.DetectorAaveGov
    io.syspulse.ext.sentinel.DetectorSnapshotGov
    """

detector {
    did="DetectorAaveGov"
}

detector {
    did="DetectorSnapshotGov"
}
