include "default-core"
include "application-dev.conf"

# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"

detectors="io.syspulse.ext.sentinel.DetectorAaveGov"

#"proposal_ids": "400,398,371",
# "api_key": "ee1eec9e5b0dc51fef435de760a14269"

detector {
    did = "DetectorAaveGov"

    contract="Aave Governance"
    
    conf="""{ 
        "cron":"30000", 
        "proposal_count": 10,
        "proposal_ids": "",
        "track_active": true,
        "track_cancelled": true,
        "track_executed": true,
        "api_key": ""
    }"""

    # feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/test-0001/END"
    output="err://"
}
