include "default-core"

include "detector-bundle.conf"

blockchains="""
    ethereum=1=https://rpc3-ethereum-mainnet,
    arbitrum=42161=https://rpc3-arbitrum-mainnet,
    optimism=10=https://rpc3-optimism-mainnet,
    polygon=137=https://rpc3-polygon-mainnet,
    bsc=56=https://rpc3-bsc-mainnet,

    # ethereum=1=https://eth.llamarpc.com,
    # arbitrum=42161=https://arb1.lava.build,
    # optimism=10=https://optimism-mainnet.public.blastapi.io,
    # polygon=137=https://polygon.gateway.tenderly.co,
    # bsc=56=https://rpc-bsc.48.club,

    gnosis=100=https://rpc.gnosis.gateway.fm,
    avalanche=43114=https://avalanche-c-chain-rpc.publicnode.com,
    fantom=250=https://rpc3.fantom.network,
    scroll=534352=https://rpc.scroll.io,
    zksync=324=https://mainnet.era.zksync.io,
    
    linea=59144=https://rpc.linea.build,
    base=8453=https://base.llamarpc.com,
    blast=81457=https://blast.drpc.org,
    polygon-zkevm=1101=https://zkevm-rpc.com,
    telos=40=https://rpc.telos.net,

    anvil=31337=https://anvil.dev.hacken.cloud,
    ethereum_sepolia=11155111=https://rpc3-ethereum-sepolia,
    ethereum_holesky=17000=https://rpc.ankr.com/eth_holesky,
    polygon_amoy=80002=https://api.zan.top/polygon-amoy,
    # base_sepolia=84532=https://sepolia.base.org,

    tron=728126428=https://api.trongrid.io/jsonrpc,
    zeta=7000=https://zetachain-mainnet.g.allthatnode.com/archive/evm
    """
