include "default-core"

detectors="""
    io.syspulse.ext.sentinel.DetectorAaveGov,
    io.syspulse.ext.sentinel.DetectorSnapshotGov,
    io.syspulse.ext.sentinel.DetectorNews,
    io.syspulse.ext.sentinel.DetectorFeed,
    io.syspulse.ext.sentinel.DetectorWar,    
    """

detector {
    did="DetectorAaveGov,DetectorSnapshotGov,DetectorNews,DetectorFeed,DetectorWar"
}
