include "default-core"

detectors="""
    io.syspulse.ext.sentinel.DetectorAaveGov,
    io.syspulse.ext.sentinel.DetectorNews,
    io.syspulse.ext.sentinel.DetectorWar,

    io.syspulse.ext.sentinel.DetectorWorkflowAudit,
    io.syspulse.ext.sentinel.DetectorWorkflowPoR,
    io.syspulse.ext.sentinel.DetectorWorkflowSimple,
    io.syspulse.ext.sentinel.DetectorWorkflowMonitoring,
    io.syspulse.ext.sentinel.DetectorWorkflowDeployment,
    io.syspulse.ext.sentinel.DetectorWorkflowIncident,
    io.syspulse.ext.sentinel.DetectorWorkflowSecurity,
    io.syspulse.ext.sentinel.DetectorWorkflowBackup,
    io.syspulse.ext.sentinel.DetectorWorkflowPentest,
    io.syspulse.ext.sentinel.DetectorWorkflow,
    """

detector {
    did="DetectorAaveGov,DetectorNews,DetectorWar,DetectorWorkflowAudit,DetectorWorkflowPoR,DetectorWorkflowSimple,DetectorWorkflowMonitoring,DetectorWorkflowDeployment,DetectorWorkflowIncident,DetectorWorkflowSecurity,DetectorWorkflowBackup,DetectorWorkflowPentest,DetectorWorkflow"
}
