include "default-core"
include "application-dev.conf"

# output="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.attack-detector.event"
feed="null://"

detectors="io.syspulse.ext.sentinel.DetectorBubblemaps"

detector {
    did = "DetectorBubblemaps"

    #contract="0x50f88fe97f72cd3e75b9eb4f747f59bceba80d59"
    chain="ethereum"

    feed="kafka://haas-dev-kafka1.hacken.dev:9092/extractor.sync.detector/sentry-bubbles/END"
    output="err://"
}
